- Dockerfile.build
- Dockerfile.deploy
- cico_build_deploy.sh
- nginx.conf
- scripts/entrypoint.sh
This PR let's us build generator-frontend in CentOS CI (once we add it to https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml)
Right now it pushes only to registry.ci.centos.org, Docker Hub can/will be added later.
> Add CentOS CI build script and Dockerfiles

- scripts/entrypoint.sh
This is not useful as frontend needs external URL for backend anyway.
> Remove default OpenSHift env var

- src/app/wizard/intro/intro.component.html
- src/app/wizard/intro/intro.component.scss
Still TODO: add images of runtimes, Erik to review my frontend CSS and HTML crap
@edewit Mind a review and adding the images of the runtimes, centered, as indicated?  It's OK to put 'em on white BGs; I know we already have transparent images so just use your best judgement.
> Updated copy for #81

- src/app/shared/forge.service.ts
- src/app/shared/model.ts
- src/app/wizard/deploy/deploy.component.ts
@gastaldi in the case we had yesterday where we get a 200 response code back with the html:
```html
<html><head><title>Error</title></head><body>Internal Server Error</body></html>
```
The error will be written in the page like this:
`Uncaught SyntaxError: Unexpected token < in JSON at position 0`
That is better but we might want to have a non 200 status code and a better message
The 412 we had yesterday will be displayed nice now
> improve error handling

- src/app/wizard/wizard.module.ts
@gastaldi this makes the base href dynamic, it can be anything now.
To test:
```bash
$ npm start
```
open `http://localhost:8088/launch/`
> dynamic base href so that we can also be called '/launch/'

- src/app/shared/keycloak.service.ts
@quintesse passes all the info from keycloak to identify example info:
```json
{
"jti": "1379054b-b8b4-442a-adb1-d69e3a16984d",
"exp": 1516381557,
"nbf": 0,
"iat": 1516381497,
"iss": "http://localhost:8280/auth/realms/master",
"aud": "openshiftio-public",
"sub": "18b9c78f-eb0c-4831-aeac-2ca0e467e5fa",
"typ": "Bearer",
"azp": "openshiftio-public",
"nonce": "4ba36b28-c1fd-4832-8283-4245e85642e7",
"auth_time": 1516381494,
"session_state": "3284773f-75c2-4eee-8637-ad7d70ff01d9",
"acr": "1",
"allowed-origins": [
"*"
],
"realm_access": {
"roles": [
"uma_authorization"
]
},
"resource_access": {
"account": {
"roles": [
"manage-account",
"manage-account-links",
"view-profile"
]
}
},
"name": "Erik de Wit",
"preferred_username": "edewit",
"given_name": "Erik",
"family_name": "de Wit",
"email": …
```
> pass all user information to identify analytics

- src/app/wizard/pages/intro/intro.component.html
- src/app/wizard/pages/runtime/runtime.page.ts
This is for the eventual removal of the tech preview ribbon for the node.js logo
I think these were the only locations for them
NOT TO BE MERGED YET
> task: remove tech preview ribbon from Node.js logo

- Dockerfile.build
@edewit this should enable the build to use Node.js 8.9.4. Give it a try before pushing to master. 
Make sure to run `CICO_LOCAL=true bash cico_build_deploy.sh` to check if the build works
> update(nodejs): Update to Node.js 8.9.4

- src/app/wizard/services/app-launcher-project-progress.service.ts
Copied from https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/space/app-launcher/services/app-launcher-project-progress.service.ts#L21-L24
> fix: WebSocket URL building is now the same as in fabric8-ui

- src/app/wizard/services/app-launcher-project-summary.service.ts
When zip is chosen as the deployment cluster will be null
fixes #275
> fix (new-ui): cluster can be null for zip download

- src/app/shared/forge.enhance.service.ts
fixes: #305 
@cmoulliard fix in the old UI to make show mission description from the catalog
> fix: use catalog as fallback mission description

- Dockerfile.deploy.rhel
- cico_build_deploy.sh
Enable build on RHEL if TARGET=rhel.
- The build scripts will be executed twice on the same machine, once for
CentOS and one for RHEL
- `docker login` is required to run `docker build`
- The image target is different if TARGET=rhel
- There is a separate Dockerfile for the RHEL build
> Build on RHEL

- src/app/shared/keycloak.service.ts
> fix: can't create account links when user is not logged in

- src/app/wizard/pages/intro/intro.component.html
I seems to remember there was another place to be modified like we did in https://github.com/fabric8-launcher/launcher-frontend/pull/231/files but I can not find it any more.
> Removed tehc preview ribbon from Fuse runtime.

- src/app/shared/error.component.ts
Dialog example: https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-frontend/settings/user-feedback/
Related to #325
> feat: show error reporting dialog when JS errors are captured

- src/app/shared/keycloak.service.ts
fixes: https://github.com/fabric8-launcher/launcher-backend/issues/496
This was accidentally introduced by this commit: https://github.com/fabric8-launcher/launcher-frontend/commit/b964ad37ea0403c3043077a9c82e8daafc116aa2#diff-0a354681939e046826a694eeefcc3921L120
Removed all the info from the dummy token making it less long.
> fix: changed to smaller valid JWT token

- src/app/wizard/services/http.service.ts
The backend may be configured to use Gitea or any other Git provider, therefore passing a fixed value as 'GitHub' will not work.
This header must be set according to the chosen Git Provider as returned by the /api/services/git/providers endpoint from the launcher-backend service.
> fix(git): Remove fixed X-Git-Provider header value

- packages/launcher-app/public/index.html
This is only when script is not loaded yet. At the same time it shows that the launcher app server is on (in case of script errors)
> Feat loading script

- nginx.conf
Adds a reverse proxy to https://github.com/login/oauth/access_token as an attempt to avoid CORS
> chore: add reverse proxy to Github

- packages/launcher-client/src/client/impl/default.launcher.client.ts
Git Auth is required for import flow but there's no way to do it. Probably the fix is to ensure Git Auth is not required, because it's not used
> fix: we don't need git oauth on import

- packages/launcher-client/src/client/impl/default.launcher.client.ts
- packages/launcher-component/src/core/project-name-input/project-name-input.tsx
fixing: #1294 
@gastaldi though while testing against preprod I get 400 responses
```
curl 'https://forge.api.prod-preview.openshift.io/api/services/openshift/projects/roomy-turn' --head 
```
> fix: now catches the 404 and returns the proper result

- packages/launcher-app/.env.openshift
- packages/launcher-app/src/app/config.ts
- packages/launcher-app/src/auth/impl/openshift-authentication-api.spec.ts
- packages/launcher-app/src/auth/impl/openshift-authentication-api.ts
- packages/launcher-app/src/auth/types.ts
- packages/launcher-component/src/hubs/dest-repository-hub.tsx
fixing: #1298
For testing install gitea locally and configure oauth2 [like described](https://docs.gitea.io/en-us/oauth2-provider/)
As gitea doesn't support wildcard redirects I've added a redirect property in the config.
> fix: added support for gitea oath2

- packages/launcher-component/src/analytics/analytics-context.ts
- packages/launcher-component/src/analytics/analytics.ts
- packages/launcher-component/src/analytics/index.ts
- packages/launcher-component/src/core/text-input/text-input.tsx
- packages/launcher-component/src/flows/create-new-app-flow.tsx
- packages/launcher-component/src/flows/deploy-example-app-flow.tsx
- packages/launcher-component/src/flows/import-existing-flow.tsx
- packages/launcher-component/src/flows/launch-flow.tsx
- packages/launcher-component/src/index.ts
- packages/launcher-component/src/pickers/dependencies-picker.tsx
- Add base/generic `Analytics` interface
- Add `AnalyticsContext` and `useAnalytics` (default analytics is just logging)
- use analytics in flows, in dependency picker and in text input
- implementation is in charge of implementing and defining the Analytics implementation (and calling init)
> feat: introduce analytics context

- packages/launcher-component/src/analytics/google-analytics.ts
This makes sure that GA can associate later events with the page they happened in.
> Make sure page URLs are set globally for GA
