package.json
src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts
src/app/wizard/wizard.module.ts

replaced multi select with component

---

src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts

partially fixing issue #1 the other part was how booleans where serialised

removed not working dynamic type attribute

---

package.json
src/app/wizard/forge.service.ts
src/app/wizard/model.ts
src/app/wizard/wizard.component.ts
typings.json

use 'Content-Disposition' for the filename test with the https://github.com/obsidian-toaster/generator-backend/pull/8 PR

use ‘Content-Disposition’ as filename for the download

---

cico_build_deploy.sh

Fixing the build failure (https://ci.centos.org/view/Devtools/job/devtools-generator-frontend-build-master/1/console)

Fix failing cp in CI script

---

cico_build_deploy.sh

This PR should enable push to Docker Hub once https://github.com/almighty/almighty-jobs/pull/124 is merged

Add Docker Hub Push

---

openshift/obsidian-generator.combined.yaml

See issue #39 
"We have 3 OpenShift templates for each of the 3 components in the Obsidian project but we want a single combined one that will create all the necessary applications in one step."

Combined template 39

---

src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts

fixes #46 no longer disables the button when validating, but waits for validate to finish

better way to wait on validation to finish

---

src/app/footer/footer.component.html

fixed footer-link

---

src/app/wizard/deploy/deploy.component.html
src/app/wizard/deploy/deploy.component.ts

introduced error and refactored to use one state

---

config/webpack.common.js
config/webpack.test.js
package.json
src/app/app-routing.module.ts
src/app/shared/forge.service.ts
src/app/shared/gui.service.ts
src/app/shared/model.ts
src/app/shared/project-select.ts
src/app/wizard/deploy/deploy.component.html
src/app/wizard/deploy/deploy.component.ts
src/app/wizard/intro/intro.component.ts
src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts
src/app/wizard/wizard.module.ts
src/assets/adoc.index
src/tests/form.spec.ts
src/tests/history.spec.ts

creates pages using the gui.service and saves state in the url also adds asciidoc content via a index file on build time

Page layout

---

package.json
src/app/wizard/deploy/deploy.component.html
src/app/wizard/deploy/deploy.component.ts
src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts
src/assets/adoc.index

added summery:
And texts on the status steps:
The texts should probroly be adjusted to something better PR for that is here: https://github.com/openshiftio/appdev-documentation/pull/190

Deploy component

---

src/app/footer/footer.component.html
src/app/footer/footer.component.scss
src/app/header/header.component.html
src/app/header/header.component.scss
src/app/wizard/wizard.component.html

part of the comments given in:
https://github.com/fabric8io/fabric8-ux/issues/403#issuecomment-297206804

change to use same header and footer as openshift.io

---

src/app/shared/model.ts
src/app/wizard/pages/deploy/deploy.component.ts
src/app/wizard/wizard.component.ts
src/tests/history.spec.ts

only show UI when fully loaded

---

src/assets/adoc.index

Merge this PR when https://github.com/openshiftio/appdev-documentation/pull/256 is merged

Fixed file name typo

---

src/assets/adoc.index

@cmoulliard once this doc has been created this can be merged
see: https://github.com/openshiftio/appdev-documentation/pull/271

added circuit breaker doc

---

scripts/entrypoint.sh
src/index.html

This should be enough, right @edewit ?

Fixed #130 Take Segment tracking key from env var

---

src/app/header/header.component.html

The 'Log out' button doesn't work in this case too.

Remove 'Fake User' when keycloak is not set up

---

package.json
src/app/shared/model.ts
src/app/wizard/components/step/step.component.html
src/app/wizard/pages/deploy/deploy.page.html
src/app/wizard/pages/deploy/deploy.page.scss
src/app/wizard/pages/deploy/deploy.page.ts
src/app/wizard/pages/generic/generic.page.html
src/app/wizard/pages/nextSteps/nextSteps.page.html
src/app/wizard/pages/nextSteps/nextSteps.page.scss
src/app/wizard/pages/nextSteps/nextSteps.page.ts
src/app/wizard/wizard.component.html
src/app/wizard/wizard.component.ts
src/app/wizard/wizard.module.ts
src/assets/adoc.index

introduce "Next steps" "page" with links to console and github

Next steps

---

src/app/wizard/pages/projectInfo/projectInfo.page.html

Now displaying a dropdown for runtime versions when they are available (#146)

Support runtime version

---

src/app/wizard/pages/deploy/deploy.page.html

Text on download page was in docs as well as static on the page. Moved to be in docs alone

removed duplicated text

---

src/app/shared/forge.service.ts
src/app/wizard/wizard.component.ts

fixing issue #138 
@gastaldi now also logs that the service is unavailable

retry 3 back-end http calls times and log error

---

src/app/shared/authentication.directive.ts

fixes issue https://github.com/openshiftio/appdev-planning/issues/48

authenticate regardless if ci is chosen

---

src/app/shared/forge.enhance.service.ts
src/app/shared/forge.service.ts
src/app/wizard/wizard.component.ts
src/app/wizard/wizard.module.ts

This way the controller has no knowledge that some of the wizard steps are client side generated.

introduced service wrapper to add the extra wizard steps

---

src/app/shared/forge.enhance.service.ts

fixed intro text

---

src/app/wizard/components/button/button.component.html
src/app/wizard/components/button/button.component.ts

make buttons float on long content

---

src/app/wizard/pages/generic/generic.page.ts
src/app/wizard/pages/projectInfo/projectInfo.page.html
src/app/wizard/pages/projectInfo/projectInfo.page.ts

move github repo to additional properties and update always

---

src/app/wizard/pages/projectInfo/projectInfo.page.ts

prefix openShift project name with username

---

npm-shrinkwrap.json
package.json
src/app/shared/keycloak-token.provider.ts
src/app/shared/keycloak.service.ts
src/app/wizard/wizard.module.ts

@gastaldi made getToken async to resolve the issue fixed #203

made token provider async

---

src/index.html

cache control

---

src/app/wizard/pages/linkAccounts/link-accounts.page.html

https://github.com/fabric8-launcher/launcher-planning/issues/76

fix issue #76

---

src/app/app-routing.module.ts
src/app/app.component.ts
src/index.html

calling page function when the angular "page" changes. This will improve initial load of the page and give better data to the analytics service

improve analytics and page load time

---

src/app/shared/keycloak.service.ts
src/app/wizard/components/project-name-input/project-name-input.component.ts

fixing issue https://github.com/fabric8-launcher/launcher-planning/issues/91

only use prefix with keycloak

---

README.md

add instrucitons to the README for running a local backend

---

src/app/shared/keycloak.service.ts

init success doesn't mean logged in

---

src/app/wizard/wizard.component.html

Don't show the loading screen when you need to login

remove loading dialog when one needs to login

---

src/app/wizard/pages/deployment/deployment.page.html

Even though all tokens have been configured correctly optionally one could change it

add configure token button

---

README.md
src/app/wizard/pages/intro/intro.component.html
src/app/wizard/pages/intro/intro.component.scss

fix(intro) change to 2 rows

---

npm-shrinkwrap.json
package.json

fixes the:
```
Cannot read property '$new' of undefined
at Object.Opal.bridge
```

chore(package): updated dependency of asciidoctor

---

cico_run_tests.sh

It basically does the same as `cico_build_deploy.sh` without the PUSH part

fix: fixes PR build

---

src/app/wizard/new-wizard.component.html
src/app/wizard/new-wizard.component.ts
src/app/wizard/pages/getting-started/getting-started.component.html
src/app/wizard/pages/getting-started/getting-started.component.ts

@gastaldi moved it to before the "back" screen

fix (new-ui): move the login flow to before asking for the project name

---

config/webpack.dev.js
config/webpack.prod.js
npm-shrinkwrap.json
package.json
src/app/wizard/services/app-launcher-dependency-check.service.ts
src/app/wizard/services/app-launcher-project-summary.service.ts

@gastaldi fixes the cluster header param

New ui update

---

src/app/shared/keycloak.service.ts

fix: use location.href if redirect is undefined

---

npm-shrinkwrap.json
package.json
src/app/wizard/services/app-launcher-gitprovider.service.ts
src/app/wizard/services/app-launcher-target-environment.service.ts
src/app/wizard/services/app-launcher-token.service.ts
src/app/wizard/wizard.module.ts

depended on https://github.com/fabric8-launcher/ngx-launcher/pull/165 and a new release

fix: getting the clusters the user is authenticated for

---

src/app/wizard/pages/intro/intro.component.scss
src/index.html

@quintesse you like this right :grin:

"Loading..." screen

---

cico_build_deploy.sh

This bug was introduced by:
https://github.com/fabric8-launcher/launcher-frontend/pull/315/files

Fixes build

---

src/app/app.component.html
src/app/app.module.ts
src/app/footer/footer.component.html
src/app/footer/footer.component.ts
src/app/wizard/pages/intro/intro.component.html
src/app/wizard/wizard.component.html
src/app/wizard/wizard.module.ts

footer in the old UI was no longer on the end of the page this fixes that

fix: footer regression

---

src/app/header/header.component.html
src/app/header/header.component.ts

fix: right style class for header navigation bar

---

npm-shrinkwrap.json
package.json

revert all of dependency bots PRs

Revert bot

---

src/app/wizard/pages/intro/intro.component.html
src/app/wizard/pages/intro/intro.component.scss

feature: added link to beta gui

---

src/app/header/header.component.html
src/app/header/header.component.ts

Header needs to be above the content. Plus made 'frontpage' boolean more logic

fix: style on intro screen header

---

npm-shrinkwrap.json
package.json
src/app/wizard/pages/getting-started/getting-started.component.html
src/app/wizard/pages/getting-started/getting-started.component.scss
src/app/wizard/pages/getting-started/getting-started.component.ts
src/app/wizard/services/app-launcher-dependency-check.service.ts
src/app/wizard/wizard.module.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/340

fix: updated to new design

---

openshift/template.yaml

Add optional to:
- LAUNCHER_BACKEND_URL
- LAUNCHER_KEYCLOAK_CLIENT_ID
- LAUNCHER_TRACKER_SEGMENT_TOKEN
- LAUNCHER_SENTRY_DSN

fix: clean openshift config map

---

npm-shrinkwrap.json
package.json
src/app/wizard/services/app-launcher-dependency-check.service.ts
src/app/wizard/wizard.module.ts

@gastaldi introducing images
Although the build is broken because the documentation for the old UI has been removed

fix: ngx-launcher updated to latest version

---

npm-shrinkwrap.json
package.json
src/app/wizard/services/app-launcher-target-environment.service.ts
src/app/wizard/services/app-launcher-token.service.ts

update ngx-launcher version to `0.1.11`.
Related to: https://github.com/fabric8-launcher/ngx-launcher/issues/217

fix: improve cluster authorization

---

package-lock.json
package.json

fix: update patternfly version to 3.30.1

---

package-lock.json
package.json

@ia3andy with the removal of the old UI we also no longer need these packages.

chore: remove unused package and update home page

---

src/app/wizard/services/app-launcher-pipeline.service.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/376

fix: no need to query pipelines in launch

---

src/app/shared/keycloak.service.ts

fix: fixes Cannot read property 'tokenParsed' of null error

---

src/app/app-routing.module.ts
src/app/shared/authguard.service.ts
src/app/wizard/wizard.module.ts

fix: introduced auth guard

---

src/app/wizard/services/app-launcher-gitprovider.service.spec.ts
src/app/wizard/services/app-launcher-gitprovider.service.ts
src/app/wizard/services/app-launcher-mission-runtime.service.ts
src/app/wizard/services/app-launcher-project-summary.service.ts
src/app/wizard/services/app-launcher-token.service.ts
src/app/wizard/services/http.service.ts

fixed the bugs that crept in earlier

fix: removed duplicate code into abstract base

---

.gitignore
package-lock.json
package.json
src/app/app.module.ts

Added `ngx-base` as a module dependency, so that it can be injected in `ngx-launcher`

fix: added ngx-base as a dependency

---

src/main.ts

fixes: https://github.com/fabric8-launcher/ngx-launcher/issues/288

fix: setup static injector

---

config/webpack.common.js
package.json
src/app/shared/config.component.ts
yarn.lock

feat: add git rev to settings

---

src/app/shared/keycloak.service.ts
src/assets/keycloak/keycloak.js

Reverts fabric8-launcher/launcher-frontend#388

Revert "fix: use iframe instead of redirect"

---

config/webpack.common.js
src/app/shared/keycloak.service.ts

fix: try fix npe

---

cico_build_deploy.sh
src/environments/environment.ts

fix: enable prod mode for angular in prod builds

---

src/app/shared/keycloak.service.ts

fix: deep check authz for isAuthenticated

---

package.json
yarn.lock

Reverts fabric8-launcher/launcher-frontend#579

Revert "build(deps): bump patternfly-ng from 3.11.2 to 4.0.0"

---

src/app/wizard/pages/getting-started/getting-started.component.html
src/app/wizard/pages/getting-started/getting-started.component.scss
src/app/wizard/pages/getting-started/getting-started.component.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/497

fix (getting started): updated the error styles and validation

---

package.json
yarn.lock

Reverts fabric8-launcher/launcher-frontend#635

Revert "build(deps): bump patternfly-ng from 3.11.2 to 4.2.2"

---

src/app/shared/keycloak.auth.service.spec.ts
src/app/shared/keycloak.auth.service.ts

Logout was not propetly working

fix(kc): logout url needs to be set after init

---

src/app/app.component.spec.ts
src/app/wizard/services/app-launcher-gitprovider.service.spec.ts
src/app/wizard/services/app-launcher-gitprovider.service.ts

- uses new git `/user` api (need backend in prod before promoting)
Closes #704

fix: add cache to git service for repositories

---

src/app/wizard/pages/intro/intro.component.html
src/app/wizard/pages/intro/intro.component.scss

Fixes https://github.com/fabric8-launcher/launcher-planning/issues/181

fix(ui): Remove Spring Boot logo

---

package.json
src/app/wizard/services/app-launcher-dependency-check.service.ts
src/app/wizard/services/app-launcher-gitprovider.service.spec.ts
src/app/wizard/services/app-launcher-gitprovider.service.ts
src/app/wizard/services/app-launcher-project-summary.service.ts
src/app/wizard/wizard.component.html
yarn.lock

That brings us a more extendable / modular front-end

Integrate the new version ngx-launcher

---

src/app/shared/keycloak.auth.service.ts

fix: refresh the token when it expires

---

src/app/wizard/services/app-launcher-target-environment.service.ts
src/app/wizard/wizard.component.html

changes: https://github.com/fabric8-launcher/ngx-launcher/pull/541

fix: copy andrew

---

src/app/wizard/services/http.service.ts

fix: check error exists

---

package.json
src/app/wizard/pages/intro/intro.component.ts
yarn.lock

feat: generate a random project name

---

package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/shared/keycloak.auth.service.spec.ts
src/app/shared/keycloak.auth.service.ts
src/app/wizard/services/app-launcher-analytic.service.ts
src/app/wizard/wizard.component.ts
src/app/wizard/wizard.module.ts
src/index.html
yarn.lock

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/590

fix: "catch" ngx-launcher events for segement in seperate service

---

src/pickers/example-picker/__tests__/example-picker.stories.tsx
src/pickers/example-picker/example-loader.tsx
src/pickers/example-picker/example-picker.tsx
src/pickers/repo-picker/__tests__/repo-picker.stories.tsx
src/pickers/repo-picker/repo-loader.tsx
src/pickers/repo-picker/repo-picker.tsx

@ia3andy added the dropdown, but there are some css issues

fix: added runtime dropdown

---

package.json
src/loaders/example-catalog-loader.tsx
src/pickers/example-picker/__tests__/example-picker.stories.tsx
src/pickers/example-picker/example-picker.tsx
yarn.lock

works when https://github.com/fabric8-launcher/launcher-client/pull/5 is merged

fix: added version dropdown

---

packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/misc/download-next-steps.tsx

fix: added download button

---

packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/misc/launch-next-steps.tsx

fix: use links from status messages

---

packages/launcher-client/src/client/data-examples/mock-git-providers.json
packages/launcher-client/src/client/impl/default.launcher.client.ts
packages/launcher-client/src/client/impl/mock.launcher.client.ts
packages/launcher-client/src/client/launcher.client.ts
packages/launcher-client/src/client/types.ts

@ia3andy build fails, but I think that is an error this is supported since typescript 2.4

fix: added git provider endpoint

---

packages/launcher-component/src/core/data-loader/data-loader.tsx

fix: <EmptyStateBody creates a <p> this there for can't create a <div

---

packages/launcher-component/package.json
packages/launcher-component/src/flows/create-example-app-flow.tsx
packages/launcher-component/src/flows/create-new-app-flow.tsx
yarn.lock

feat(git): generate a random project name

---

packages/launcher-component/src/pickers/example-picker.tsx

fix: removed default selected values

---

packages/keycloak-react/src/impl/keycloak-authentication-api.ts
packages/launcher-component/package.json
packages/launcher-component/src/flows/create-new-app-flow.tsx
packages/launcher-component/src/flows/deploy-example-app-flow.tsx
packages/launcher-component/src/flows/import-existing-flow.tsx
packages/launcher-component/src/launcher/launcher.tsx
yarn.lock

fix: use session storage to save user's selection

---

packages/launcher-component/src/pickers/buildimage-picker.tsx

fix: changed build image select into advanced section

---

packages/launcher-client/src/client/impl/mock.launcher.client.ts
packages/launcher-client/src/client/types.ts
packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/misc/launch-next-steps.tsx

fix: show welcome app link

---

packages/launcher-component/src/pickers/repository-picker.module.scss
packages/launcher-component/src/pickers/user-repository-picker.tsx

fix: removed import and improved styles

---

packages/launcher-component/src/core/hub-n-spoke/index.tsx

fix: added close button

---

packages/launcher-component/src/core/hub-n-spoke/index.tsx

fix: don't show hint on error

---

packages/launcher-component/src/pickers/user-repository-picker.tsx

fix: now takes duplicate repo into account

---

packages/launcher-component/src/core/data-loader/data-loader.tsx
packages/launcher-component/src/core/hub-n-spoke/index.tsx
packages/launcher-component/src/core/stuff.tsx

fix: show error when data fails to load

---

packages/launcher-client/src/client/impl/mock.launcher.client.ts
packages/launcher-component/src/flows/launch-flow.tsx

fix: use all links in routes, not just the first

---

packages/keycloak-react/src/auth-router.tsx
packages/launcher-app/src/config.ts
packages/launcher-app/src/launcher-app.scss
packages/launcher-app/src/launcher-app.tsx
packages/launcher-app/src/layout.tsx
packages/launcher-component/src/core/stuff.tsx
packages/launcher-component/src/flows/create-new-app-flow.tsx
packages/launcher-component/src/flows/deploy-example-app-flow.tsx
packages/launcher-component/src/flows/import-existing-flow.tsx
packages/launcher-component/src/index.ts
packages/launcher-component/src/launcher/__tests__/launcher.stories.tsx
packages/launcher-component/src/launcher/launcher.tsx

feat: add routing for the app

---

packages/launcher-component/src/flows/launcher-client-adapters.ts

fix: cluster selection can be empty

---

packages/keycloak-react/src/authentication-api.ts
packages/keycloak-react/src/impl/authentication-api-react-state-proxy.tsx
packages/keycloak-react/src/impl/keycloak-authentication-api.ts
packages/keycloak-react/src/impl/mock-authentication-api.ts
packages/keycloak-react/src/impl/no-authentication-api.ts
packages/launcher-app/src/layout.tsx

feat: add manage account link in toolbar

---

packages/launcher-component/src/hubs/dest-repository-hub.tsx
packages/launcher-component/src/loaders/git-info-loader.tsx
packages/launcher-component/src/pickers/__tests__/user-repository-picker.stories.tsx
packages/launcher-component/src/pickers/user-repository-picker.tsx

fix: now offers to connect github account

---

packages/launcher-app/src/login-page.module.scss
packages/launcher-app/src/login-page.tsx

fix: made login boxes even nicer

---

packages/launcher-component/src/loaders/buildimage-loader.tsx

fix: filter out empty env vars

---

packages/launcher-client/src/client/helpers/launchers.ts
packages/launcher-component/src/hubs/example-hub.tsx
packages/launcher-component/src/loaders/example-catalog-loader.tsx
packages/launcher-component/src/pickers/__tests__/example-picker.stories.tsx
packages/launcher-component/src/pickers/example-picker.tsx

fix: use versions as specified by the booster

---

packages/launcher-client/src/client/http.service.spec.ts
packages/launcher-client/src/client/http.service.ts
packages/launcher-component/src/core/stuff.tsx

also see: https://github.com/axios/axios#handling-errors for more info.
fixes: #1100

fix: send all error information allong

---

packages/launcher-client/src/client/helpers/launchers.ts
packages/launcher-component/src/flows/deploy-example-app-flow.tsx
packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/loaders/openshiftcluster-loader.tsx
packages/launcher-component/src/pickers/__tests__/cluster-picker.stories.tsx
packages/launcher-component/src/pickers/cluster-picker.tsx
packages/launcher-component/src/pickers/example-picker.tsx

- introduce downloadOnly flag in Example picker value
- introduce clusterType to Cluster picker value
- display hint (and block launch) when downloadOnly flag is enabled

feat: prevent launch on istio example

---

packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/loaders/git-info-loader.tsx

fix: only when status code is 404

---

packages/launcher-component/src/pickers/buildimage-picker.tsx

fix: styles

---

packages/launcher-component/src/pickers/example-picker.tsx

fix: select first version as default

---

src/app/wizard/pages/mission-runtime-step/mission-runtime-step.component.ts

fix: select version that belongs to selected runtime

---

packages/launcher-client/src/client/types.ts
packages/launcher-component/src/loaders/buildimage-loader.tsx

fix: metadata on builder image is optional

---

packages/launcher-client/package.json
packages/launcher-client/rollup.config.js
packages/launcher-client/src/client/impl/mock.launcher.client.ts
packages/launcher-client/src/client/launcher.client.factory.ts
yarn.lock

fix: strip mock data from build for prod

---

packages/launcher-client/src/client/helpers/launchers.ts
packages/launcher-component/src/pickers/__tests__/__snapshots__/example-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/example-picker.spec.tsx
packages/launcher-component/src/pickers/example-picker.tsx

fix: use runsOn instead of istio

---

packages/launcher-client/src/client/data-examples/mock-example-catalog.json
packages/launcher-client/src/client/helpers/launchers.spec.ts
packages/launcher-component/src/pickers/__tests__/__snapshots__/example-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/example-picker.spec.tsx
packages/launcher-component/src/pickers/example-picker.tsx

fix: Only examples with `runsOn: none` are `downloadOnly`

---

packages/launcher-client/src/client/data-examples/mock-clusters.json
packages/launcher-component/src/pickers/__tests__/__snapshots__/cluster-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/cluster-picker.spec.tsx
packages/launcher-component/src/pickers/cluster-picker.tsx

fix: impossible to select cluster when there is no connected cluster

---

packages/launcher-component/src/core/text-input/text-input.tsx
packages/launcher-component/src/pickers/__tests__/__snapshots__/maven-settings-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/__snapshots__/nodejs-settings-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/maven-settings-picker.spec.tsx
packages/launcher-component/src/pickers/__tests__/maven-settings-picker.stories.tsx
packages/launcher-component/src/pickers/__tests__/nodejs-settings-picker.spec.tsx
packages/launcher-component/src/pickers/__tests__/nodejs-settings-picker.stories.tsx
packages/launcher-component/src/pickers/maven-settings-picker.tsx
packages/launcher-component/src/pickers/nodejs-settings-picker.tsx

Introduced maven and nodjs "GAV" pickers

---

packages/launcher-client/src/client/types.ts

fix: send project name on download

---

packages/launcher-component/src/core/hub-n-spoke/index.tsx
packages/launcher-component/src/core/inline-text-input/__tests__/__snapshots__/inline-text-input.spec.tsx.snap
packages/launcher-component/src/core/inline-text-input/__tests__/inline-text-input.spec.tsx
packages/launcher-component/src/core/inline-text-input/inline-text-input.module.scss
packages/launcher-component/src/core/inline-text-input/inline-text-input.tsx
packages/launcher-component/src/flows/__tests__/__snapshots__/create-new-app-flow.spec.tsx.snap
packages/launcher-component/src/flows/__tests__/__snapshots__/deploy-example-app-flow.spec.tsx.snap
packages/launcher-component/src/flows/__tests__/create-new-app-flow.spec.tsx
packages/launcher-component/src/flows/__tests__/deploy-example-app-flow.spec.tsx
packages/launcher-component/src/flows/create-new-app-flow.tsx
packages/launcher-component/src/flows/deploy-example-app-flow.tsx
packages/launcher-component/src/flows/launch-flow.tsx
packages/launcher-component/src/flows/launcher-client-adapters.ts

fix: inline text editor to edit project name

---

packages/launcher-component/src/flows/__tests__/create-new-app-flow.spec.tsx
packages/launcher-component/src/pickers/runtime-picker.tsx

fix: use dropdown if number of items is big

---

packages/launcher-component/src/flows/__tests__/__snapshots__/import-existing-flow.spec.tsx.snap
packages/launcher-component/src/flows/__tests__/import-existing-flow.spec.tsx
packages/launcher-component/src/flows/import-existing-flow.tsx
packages/launcher-component/src/flows/launcher-client-adapters.ts
packages/launcher-component/src/flows/types.tsx

fix: use appName input for import as well

---

packages/launcher-component/src/flows/create-new-app-flow.tsx
packages/launcher-component/src/flows/deploy-example-app-flow.tsx
packages/launcher-component/src/flows/import-existing-flow.tsx

chore: update title text

---

packages/launcher-app/src/auth/impl/openshift-authentication-api.ts

fix: encode redirect url

---

packages/launcher-component/src/flows/__tests__/__snapshots__/create-new-app-flow.spec.tsx.snap
packages/launcher-component/src/flows/__tests__/create-new-app-flow.spec.tsx
packages/launcher-component/src/flows/create-new-app-flow.tsx
packages/launcher-component/src/flows/types.tsx
packages/launcher-component/src/hubs/__tests__/forms.stories.tsx
packages/launcher-component/src/hubs/welcome-app-hub.tsx

fix: make welcome app editable hub

---

packages/launcher-component/src/core/toggle-panel/__tests__/__snapshots__/toggle-panel.spec.tsx.snap
packages/launcher-component/src/core/toggle-panel/__tests__/toggle-panel.spec.tsx
packages/launcher-component/src/core/toggle-panel/__tests__/toggle-panel.stories.tsx
packages/launcher-component/src/core/toggle-panel/toggle-panel.module.scss
packages/launcher-component/src/core/toggle-panel/toggle-panel.scss
packages/launcher-component/src/core/toggle-panel/toggle-panel.tsx
packages/launcher-component/src/flows/__tests__/import-existing-flow.spec.tsx
packages/launcher-component/src/pickers/__tests__/__snapshots__/maven-settings-picker.spec.tsx.snap
packages/launcher-component/src/pickers/__tests__/maven-settings-picker.spec.tsx
packages/launcher-component/src/pickers/__tests__/maven-settings-picker.stories.tsx
packages/launcher-component/src/pickers/buildimage-picker.tsx
packages/launcher-component/src/pickers/maven-settings-picker.scss
packages/launcher-component/src/pickers/maven-settings-picker.tsx

feat: introduce horizontal toggle-panel mode

---

packages/launcher-component/package.json
packages/launcher-component/src/index.ts

BREAKING CHANGE: most of the components have been moved to the unified repo

fix: add exports
